version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vaccinikids-db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: vaccinikids_user
      POSTGRES_PASSWORD: vaccinikids_password
      POSTGRES_DB: vaccinikids
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U vaccinikids_user -d vaccinikids']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local