const fs = require('fs');
const path = require('path');

const mobileEnv = process.env.MOBILE_ENV || 'development';
const apiBaseUrl = (process.env.API_BASE_URL || 'http://localhost:3000/api').replace(/\/+$/, '');
const allowedEnvironments = new Set(['development', 'staging', 'production']);
const quoteJsString = (value) => `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

if (!allowedEnvironments.has(mobileEnv)) {
  throw new Error(`Unsupported MOBILE_ENV: ${mobileEnv}`);
}
if (mobileEnv !== 'development' && !process.env.API_BASE_URL) {
  throw new Error('API_BASE_URL is required for staging and production mobile bundles');
}
if (mobileEnv !== 'development' && !apiBaseUrl.startsWith('https://')) {
  throw new Error('API_BASE_URL must use HTTPS for staging and production mobile bundles');
}

const output = `// Generated by \`npm run mobile:configure\`. Do not edit manually.
export const MOBILE_ENV = ${quoteJsString(mobileEnv)};
export const CONFIGURED_API_BASE_URL = ${quoteJsString(apiBaseUrl)};
`;

fs.writeFileSync(path.join(__dirname, '..', 'src', 'config', 'mobileEnvironment.js'), output);
console.warn(`Mobile configuration generated for ${mobileEnv}: ${apiBaseUrl}`);
