CREATE TABLE IF NOT EXISTS kiosk_identity (
  id SERIAL PRIMARY KEY,
  code VARCHAR(80) NOT NULL UNIQUE,
  centre_id INTEGER NOT NULL REFERENCES centre(id) ON DELETE RESTRICT,
  secret_hash VARCHAR(255) NOT NULL,
  token_version INTEGER NOT NULL DEFAULT 1,
  est_actif BOOLEAN NOT NULL DEFAULT TRUE,
  rotated_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_kiosk_identity_centre ON kiosk_identity(centre_id);
